"""
slicer.py
---------
Thin wrappers around OpenSCAD and PrusaSlicer/CuraEngine CLIs.

Pipeline:
  .scad  →[OpenSCAD]→  .stl  →[PrusaSlicer or CuraEngine]→  .gcode

All functions return (success: bool, log: str, output_path: Path | None).
"""

from __future__ import annotations
import shutil
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

# ── Executable discovery ──────────────────────────────────────────────────────

def _candidates(name_list: list[str]) -> str | None:
    for name in name_list:
        found = shutil.which(name)
        if found:
            return found
    return None


def find_openscad() -> str | None:
    platform_paths: list[str] = []
    if sys.platform == "win32":
        platform_paths = [
            r"C:\Program Files\OpenSCAD\openscad.exe",
            r"C:\Program Files (x86)\OpenSCAD\openscad.exe",
        ]
    elif sys.platform == "darwin":
        platform_paths = [
            "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD",
        ]

    found = _candidates(["openscad", "OpenSCAD"] + platform_paths)
    return found


def find_prusa_slicer() -> str | None:
    platform_paths: list[str] = []
    if sys.platform == "win32":
        platform_paths = [
            r"C:\Program Files\Prusa3D\PrusaSlicer\prusa-slicer-console.exe",
            r"C:\Program Files\PrusaSlicer\prusa-slicer-console.exe",
        ]
    elif sys.platform == "darwin":
        platform_paths = [
            "/Applications/PrusaSlicer.app/Contents/MacOS/PrusaSlicer",
        ]

    return _candidates(
        ["prusa-slicer", "prusa-slicer-console", "PrusaSlicer"] + platform_paths
    )


def find_cura_engine() -> str | None:
    platform_paths: list[str] = []
    if sys.platform == "win32":
        platform_paths = [
            r"C:\Program Files\Ultimaker Cura 5.0\CuraEngine.exe",
            r"C:\Program Files\UltiMaker Cura\CuraEngine.exe",
        ]
    elif sys.platform == "darwin":
        platform_paths = [
            "/Applications/UltiMaker Cura.app/Contents/MacOS/CuraEngine",
        ]

    return _candidates(["CuraEngine", "curaengine"] + platform_paths)


def slicer_status() -> dict:
    """Return a status dict describing what tools are available."""
    ps   = find_prusa_slicer()
    ce   = find_cura_engine()
    osc  = find_openscad()
    return {
        "openscad":      osc,
        "prusa_slicer":  ps,
        "cura_engine":   ce,
        "can_compile":   bool(osc),
        "can_slice":     bool(ps or ce),
        "slicer_type":   "prusa" if ps else ("cura" if ce else None),
    }


# ── OpenSCAD: .scad → .stl ───────────────────────────────────────────────────

def compile_to_stl(
    scad_code: str,
    output_dir: Path | None = None,
) -> tuple[bool, str, Path | None]:
    """
    Write scad_code to a temp file, call OpenSCAD to produce an STL.
    Returns (success, log_text, stl_path).
    """
    exe = find_openscad()
    if not exe:
        return False, (
            "OpenSCAD not found.\n"
            "Install it from https://openscad.org/downloads.html\n"
            "and make sure it is on your PATH."
        ), None

    work_dir = output_dir or Path(tempfile.mkdtemp(prefix="vibe_"))
    work_dir.mkdir(parents=True, exist_ok=True)

    scad_path = work_dir / "model.scad"
    stl_path  = work_dir / "model.stl"

    scad_path.write_text(scad_code, encoding="utf-8")

    cmd = [exe, "-o", str(stl_path), str(scad_path)]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

    log = (result.stdout + "\n" + result.stderr).strip()
    if result.returncode == 0 and stl_path.exists():
        return True, log, stl_path
    return False, log or "OpenSCAD exited with errors.", None


# ── Slicer config generation ──────────────────────────────────────────────────

def _prusa_config(printer_profile: dict, material: str,
                   material_temps: dict) -> str:
    """Generate a minimal PrusaSlicer INI config."""
    import printer_profiles as pp
    temps = pp.resolve_temps(printer_profile, material, material_temps)
    cx, cy = pp.bed_center(printer_profile)

    material_map = {"PLA": "PLA", "PETG": "PETG", "ABS": "ABS"}
    filament_type = material_map.get(material, "PLA")

    return textwrap.dedent(f"""\
        # PrusaSlicer config generated by Universal Vibe-to-Print Engine
        layer_height = 0.2
        first_layer_height = 0.2
        nozzle_diameter = 0.4
        filament_diameter = 1.75
        filament_type = {filament_type}
        temperature = {temps['hotend']}
        first_layer_temperature = {temps['hotend']}
        bed_temperature = {temps['bed']}
        first_layer_bed_temperature = {temps['bed']}
        bed_size = {printer_profile['bed_x']},{printer_profile['bed_y']}
        print_center = {cx:.1f},{cy:.1f}
        fill_density = 20%
        fill_pattern = gyroid
        support_material = 0
        skirts = 3
        skirt_distance = 6
        brim_width = 0
        complete_objects = 0
    """)


# ── PrusaSlicer: .stl → .gcode ────────────────────────────────────────────────

def slice_with_prusa(
    stl_path: Path,
    printer_profile: dict,
    material: str,
    material_temps: dict,
    output_dir: Path | None = None,
) -> tuple[bool, str, Path | None]:
    exe = find_prusa_slicer()
    if not exe:
        return False, "PrusaSlicer not found. Install from https://www.prusa3d.com/prusaslicer/", None

    work_dir = output_dir or stl_path.parent
    gcode_path  = work_dir / (stl_path.stem + ".gcode")
    config_path = work_dir / "slice_config.ini"

    config_path.write_text(
        _prusa_config(printer_profile, material, material_temps),
        encoding="utf-8",
    )

    cmd = [
        exe,
        "--export-gcode",
        "--load", str(config_path),
        "--output", str(gcode_path),
        str(stl_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    log = (result.stdout + "\n" + result.stderr).strip()

    if result.returncode == 0 and gcode_path.exists():
        return True, log, gcode_path
    return False, log or "PrusaSlicer exited with errors.", None


# ── CuraEngine: .stl → .gcode ────────────────────────────────────────────────

def slice_with_cura(
    stl_path: Path,
    printer_profile: dict,
    material: str,
    material_temps: dict,
    output_dir: Path | None = None,
) -> tuple[bool, str, Path | None]:
    exe = find_cura_engine()
    if not exe:
        return False, "CuraEngine not found.", None

    import printer_profiles as pp
    temps = pp.resolve_temps(printer_profile, material, material_temps)

    work_dir   = output_dir or stl_path.parent
    gcode_path = work_dir / (stl_path.stem + ".gcode")

    # CuraEngine requires a machine definition; we pass key settings inline.
    cmd = [
        exe, "slice",
        "-v",
        "-o", str(gcode_path),
        "-s", f"layer_height=0.2",
        "-s", f"material_print_temperature={temps['hotend']}",
        "-s", f"material_bed_temperature={temps['bed']}",
        "-s", f"machine_width={printer_profile['bed_x']}",
        "-s", f"machine_depth={printer_profile['bed_y']}",
        "-s", f"machine_height={printer_profile['bed_z']}",
        "-s", "infill_sparse_density=20",
        "-l", str(stl_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    log = (result.stdout + "\n" + result.stderr).strip()

    if result.returncode == 0 and gcode_path.exists():
        return True, log, gcode_path
    return False, log or "CuraEngine exited with errors.", None


# ── Unified slice entry point ─────────────────────────────────────────────────

def slice_stl(
    stl_path: Path,
    printer_profile: dict,
    material: str,
    material_temps: dict,
    output_dir: Path | None = None,
) -> tuple[bool, str, Path | None]:
    """Try PrusaSlicer first, then CuraEngine."""
    if find_prusa_slicer():
        return slice_with_prusa(stl_path, printer_profile, material,
                                 material_temps, output_dir)
    if find_cura_engine():
        return slice_with_cura(stl_path, printer_profile, material,
                                material_temps, output_dir)
    return False, (
        "No slicer found.\n"
        "Install PrusaSlicer (https://www.prusa3d.com/prusaslicer/) "
        "or CuraEngine and add it to your PATH."
    ), None


# ── Prepend G-code start sequence to an existing .gcode file ─────────────────

def prepend_start_gcode(gcode_path: Path, printer_profile: dict,
                          material: str, material_temps: dict) -> None:
    """Insert the bed-centred start sequence at the top of the G-code file."""
    import printer_profiles as pp
    header  = pp.gcode_start_snippet(printer_profile, material, material_temps)
    original = gcode_path.read_text(encoding="utf-8", errors="replace")
    gcode_path.write_text(header + "\n" + original, encoding="utf-8")
