"""
transfer.py
-----------
All file-transfer methods for getting G-code off the machine.

send_email(cfg, to_addr, gcode_path)          -> (ok, msg)
send_to_octoprint(ip, api_key, gcode_path,
                   print_now)                  -> (ok, msg)
send_to_moonraker(ip, gcode_path, print_now)  -> (ok, msg)
local_downloads_path()                         -> Path
"""

from __future__ import annotations
import smtplib
import ssl
import sys
from email.mime.application import MIMEApplication
from email.mime.multipart   import MIMEMultipart
from email.mime.text        import MIMEText
from pathlib import Path

import requests


# ── Email ─────────────────────────────────────────────────────────────────────

def send_email(
    smtp_host:  str,
    smtp_port:  int,
    username:   str,
    password:   str,
    to_addr:    str,
    gcode_path: Path,
    use_tls:    bool = True,
) -> tuple[bool, str]:
    """
    Send gcode_path as an email attachment.

    Common SMTP settings:
      Gmail    : smtp.gmail.com:465, TLS=True  (use App Password)
      Outlook  : smtp.office365.com:587, TLS=True (STARTTLS)
      Local    : localhost:25, TLS=False
    """
    if not gcode_path.exists():
        return False, f"File not found: {gcode_path}"

    subject  = f"G-Code: {gcode_path.name}"
    body     = (
        f"Your G-code file '{gcode_path.name}' is attached.\n\n"
        f"Generated by the Universal Vibe-to-Print Engine."
    )

    msg = MIMEMultipart()
    msg["From"]    = username
    msg["To"]      = to_addr
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    with gcode_path.open("rb") as fh:
        part = MIMEApplication(fh.read(), Name=gcode_path.name)
    part["Content-Disposition"] = f'attachment; filename="{gcode_path.name}"'
    msg.attach(part)

    try:
        context = ssl.create_default_context()
        if smtp_port == 465:
            with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
                server.login(username, password)
                server.sendmail(username, to_addr, msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                if use_tls:
                    server.starttls(context=context)
                server.login(username, password)
                server.sendmail(username, to_addr, msg.as_string())
        return True, f"Sent to {to_addr} via {smtp_host}:{smtp_port}."
    except smtplib.SMTPAuthenticationError:
        return False, (
            "SMTP authentication failed. "
            "For Gmail, use an App Password (not your account password)."
        )
    except Exception as exc:
        return False, f"Email error: {exc}"


# ── OctoPrint ─────────────────────────────────────────────────────────────────

def send_to_octoprint(
    ip:         str,
    api_key:    str,
    gcode_path: Path,
    print_now:  bool = False,
) -> tuple[bool, str]:
    """
    Upload a G-code file to OctoPrint (REST API v1).
    Optionally start printing immediately.
    """
    base = ip.rstrip("/")
    if not base.startswith("http"):
        base = f"http://{base}"

    headers = {"X-Api-Key": api_key}

    # ── Upload ────────────────────────────────────────────────────────────────
    try:
        with gcode_path.open("rb") as fh:
            upload_resp = requests.post(
                f"{base}/api/files/local",
                headers=headers,
                files={"file": (gcode_path.name, fh, "application/octet-stream")},
                data={"print": "true" if print_now else "false"},
                timeout=60,
            )
        upload_resp.raise_for_status()
    except requests.ConnectionError:
        return False, f"Cannot reach OctoPrint at {base}. Check the IP/port."
    except requests.HTTPError as exc:
        return False, f"OctoPrint upload failed: {exc.response.status_code} {exc.response.text}"
    except Exception as exc:
        return False, f"OctoPrint error: {exc}"

    msg = f"Uploaded '{gcode_path.name}' to OctoPrint at {base}."
    if print_now:
        msg += " Print started."
    return True, msg


# ── Moonraker / Klipper ───────────────────────────────────────────────────────

def send_to_moonraker(
    ip:         str,
    gcode_path: Path,
    print_now:  bool = False,
) -> tuple[bool, str]:
    """
    Upload a G-code file to Moonraker (Mainsail / Fluidd / Klipper).
    Moonraker does not require an API key by default.
    """
    base = ip.rstrip("/")
    if not base.startswith("http"):
        base = f"http://{base}"

    # ── Upload via /server/files/upload ───────────────────────────────────────
    try:
        with gcode_path.open("rb") as fh:
            upload_resp = requests.post(
                f"{base}/server/files/upload",
                files={"file": (gcode_path.name, fh, "application/octet-stream")},
                data={"path": "", "root": "gcodes"},
                timeout=60,
            )
        upload_resp.raise_for_status()
    except requests.ConnectionError:
        return False, f"Cannot reach Moonraker at {base}. Check the IP/port."
    except requests.HTTPError as exc:
        return False, f"Moonraker upload failed: {exc.response.status_code} {exc.response.text}"
    except Exception as exc:
        return False, f"Moonraker error: {exc}"

    if print_now:
        try:
            print_resp = requests.post(
                f"{base}/printer/print/start",
                json={"filename": gcode_path.name},
                timeout=15,
            )
            print_resp.raise_for_status()
        except Exception as exc:
            return True, f"Uploaded OK but failed to start print: {exc}"

    msg = f"Uploaded '{gcode_path.name}' to Moonraker at {base}."
    if print_now:
        msg += " Print started."
    return True, msg


# ── Local Downloads folder ────────────────────────────────────────────────────

def local_downloads_path() -> Path:
    """Return the platform's Downloads folder."""
    if sys.platform == "win32":
        import winreg
        try:
            with winreg.OpenKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders",
            ) as key:
                dl, _ = winreg.QueryValueEx(key, "{374DE290-123F-4565-9164-39C4925E467B}")
                return Path(dl)
        except Exception:
            pass
    # macOS, Linux, or Windows fallback
    return Path.home() / "Downloads"


def copy_to_downloads(gcode_path: Path) -> tuple[bool, str]:
    """Copy G-code to the user's Downloads folder."""
    import shutil
    dl_dir  = local_downloads_path()
    dl_dir.mkdir(parents=True, exist_ok=True)
    dest = dl_dir / gcode_path.name
    try:
        shutil.copy2(gcode_path, dest)
        return True, f"Saved to {dest}"
    except Exception as exc:
        return False, f"Copy failed: {exc}"
